basePath: /
host: localhost:8080
info:
  contact:
    name: Oni Oluwatomiwa
  description: This is a simple API that parsers FXQL statements/currency transactionxs
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: FXQL Parsr API
  version: "1.0"
paths: {}
swagger: "2.0"
